name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -h localhost -p 5432 -U postgres -d testdb"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          timeout 30s bash -c 'while ! pg_isready -h localhost -p 5432 -U postgres -d testdb; do sleep 1; done'

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with pytest
        run: pytest
